# Generated by Django 3.0.8 on 2020-07-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_auto_20200708_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlrequest',
            old_name='full_reponse',
            new_name='full_response',
        ),
        migrations.RenameField(
            model_name='mlrequest',
            old_name='parent_mlalgorothm',
            new_name='parent_mlalgorithm',
        ),
    ]
